### ISSUE TITLE
Gradle fails to generate jooq data.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster-jooq#1]
When running with gradle it will fail to generate jooq data.

```
2020-08-27T17:51:15.1186314Z 17:51:15.059 [main] ERROR org.jooq.codegen.GenerationTool - Cannot read /home/runner/work/generator-jhipster-jooq/generator-jhipster-jooq/app/build/tmp/generateJooq/config.xml. Error : Error while exporting schema
2020-08-27T17:51:15.1186653Z org.jooq.exception.DataAccessException: Error while exporting schema
2020-08-27T17:51:15.1186943Z 	at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:103)
2020-08-27T17:51:15.1187800Z 	at org.jooq.meta.extensions.AbstractInterpretingDatabase.create0(AbstractInterpretingDatabase.java:77)
2020-08-27T17:51:15.1188048Z 	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:274)
2020-08-27T17:51:15.1188276Z 	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:263)
2020-08-27T17:51:15.1188510Z 	at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:253)
2020-08-27T17:51:15.1188738Z 	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:521)
2020-08-27T17:51:15.1188963Z 	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:222)
2020-08-27T17:51:15.1189176Z 	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:217)
2020-08-27T17:51:15.1189398Z 	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:189)
2020-08-27T17:51:15.1189896Z Caused by: liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: config/liquibase/changelog/00000000000000_initial_schema.xml does not exist
2020-08-27T17:51:15.1190194Z 	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
2020-08-27T17:51:15.1190424Z 	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:217)
2020-08-27T17:51:15.1190630Z 	at liquibase.Liquibase.update(Liquibase.java:190)
2020-08-27T17:51:15.1190829Z 	at liquibase.Liquibase.update(Liquibase.java:179)
2020-08-27T17:51:15.1191026Z 	at liquibase.Liquibase.update(Liquibase.java:175)
2020-08-27T17:51:15.1191222Z 	at liquibase.Liquibase.update(Liquibase.java:168)
2020-08-27T17:51:15.1191468Z 	at org.jooq.meta.extensions.liquibase.LiquibaseDatabase.export(LiquibaseDatabase.java:156)
2020-08-27T17:51:15.1191749Z 	at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:100)
2020-08-27T17:51:15.1191941Z 	... 8 common frames omitted
2020-08-27T17:51:15.1192337Z Caused by: liquibase.exception.SetupException: config/liquibase/changelog/00000000000000_initial_schema.xml does not exist
2020-08-27T17:51:15.1192590Z 	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:356)
2020-08-27T17:51:15.1192829Z 	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:305)
2020-08-27T17:51:15.1193191Z 	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
2020-08-27T17:51:15.1193387Z 	... 15 common frames omitted
2020-08-27T17:51:15.1193805Z Caused by: liquibase.exception.ChangeLogParseException: config/liquibase/changelog/00000000000000_initial_schema.xml does not exist
2020-08-27T17:51:15.1194095Z 	at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:106)
2020-08-27T17:51:15.1194357Z 	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
2020-08-27T17:51:15.1194596Z 	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:565)
2020-08-27T17:51:15.1194850Z 	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:348)
2020-08-27T17:51:15.1195046Z 	... 17 common frames omitted
```

Reference https://github.com/etiennestuder/gradle-jooq-plugin/issues/138.

**Comment by lukaseder** [comment]
This reminds me of https://github.com/jOOQ/jOOQ/issues/9866, which was fixed in jOOQ 3.14.0 and 3.13.2. That seems to have solved the issues with the YAML configuration, but not necessarily with the XML configuration of Liquibase. What could be the issue?

**Comment by lukaseder** [comment]
I see you're explicitly adding `src/main/resources/` to the classpath of Liquibase itself:
https://github.com/mshima/jhipster-jooq-gradle-sample/blob/e3d13474c01439c84079e6164f8d7c777ba789c3/build.gradle#L151

But not to jOOQ. Does that explain it?

**Comment by mshima** [comment]
> This reminds me of [jOOQ/jOOQ#9866](https://github.com/jOOQ/jOOQ/issues/9866), which was fixed in jOOQ 3.14.0 and 3.13.2. That seems to have solved the issues with the YAML configuration, but not necessarily with the XML configuration of Liquibase. What could be the issue?

Seems related.
We are using 3.13.4 already, jhipster 6 uses spring boot 2.2.9 => jooq 2.12.4, but there is no liquibase support in 2.12.4.
maven is working ok, so I am assuming this is specific to gradle.

**Comment by mshima** [comment]
> I see you're explicitly adding `src/main/resources/` to the classpath of Liquibase itself:

That's generated by jhipster by default.

> https://github.com/mshima/jhipster-jooq-gradle-sample/blob/e3d13474c01439c84079e6164f8d7c777ba789c3/build.gradle#L151
> 
> But not to jOOQ. Does that explain it?

Can be, is there a way to forward that config to liquibase using gradle plugin?

**Comment by lukaseder** [comment]
See Etienne's answer here: https://github.com/etiennestuder/gradle-jooq-plugin/issues/138#issuecomment-682303968

**Comment by mshima** [comment]
> See Etienne's answer here: [etiennestuder/gradle-jooq-plugin#138 (comment)](https://github.com/etiennestuder/gradle-jooq-plugin/issues/138#issuecomment-682303968)

I'm afraid that explains how to add a dependency not a resource dir.
I don't know gradle enough.
I tried this without success:

```
jooqGenerator file("src/main/resources")
```

Got:
```
A problem occurred evaluating root project 'jhipster'.
> Cannot convert the provided notation to an object of type Dependency: /Users/mshima/aplicacoes/jooq-gradle/src/main/resources.
  The following types/formats are supported:
    - Instances of Dependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().
```

Confirmed that we are using jooq 3.13.4:
```
09:21:10.154 [main] INFO org.jooq.codegen.GenerationTool - No <inputCatalog/> was provided. Generating ALL available catalogs instead.
09:21:10.154 [main] INFO org.jooq.codegen.GenerationTool - No <inputSchema/> was provided. Generating ALL available schemata instead.
09:21:10.464 [main] DEBUG liquibase.resource.ClassLoaderResourceAccessor - Opening jar:file:/Users/mshima/.m2/repository/org/jooq/jooq-codegen/3.13.4/jooq-codegen-3.13.4.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
09:21:10.465 [main] DEBUG liquibase.resource.ClassLoaderResourceAccessor - Opening jar:file:/Users/mshima/.m2/repository/org/jooq/jooq-meta-extensions/3.13.4/jooq-meta-extensions-3.13.4.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
09:21:10.465 [main] DEBUG liquibase.resource.ClassLoaderResourceAccessor - Opening jar:file:/Users/mshima/.m2/repository/org/jooq/jooq-meta/3.13.4/jooq-meta-3.13.4.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
09:21:10.466 [main] DEBUG liquibase.resource.ClassLoaderResourceAccessor - Opening jar:file:/Users/mshima/.m2/repository/org/jooq/jooq/3.13.4/jooq-3.13.4.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
```

**Comment by atomfrede** [comment]
I will try to have a look. But most probably after 4th of September
